# Generated by Django 5.0.4 on 2025-03-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_token_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token_limit',
            field=models.IntegerField(default=0),
        ),
    ]
