# Generated by Django 5.0.4 on 2025-03-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_token_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='token_usage_this_month',
            field=models.IntegerField(default=50000),
        ),
    ]
