# Generated by Django 5.0.4 on 2025-03-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_token_usage_this_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='token_limit',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='token_reset_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='token_usage_this_month',
        ),
    ]
