# Generated by Django 5.0.4 on 2025-03-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_token_limit_and_more'),  # Adjust this to your actual previous migration
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='two_factor_backup_codes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=100),
        ),
        # Remove the following operations that reference the non-existent 'user' model
        # migrations.AddField(
        #     model_name='user',
        #     name='two_factor_backup_codes',
        #     field=models.TextField(blank=True),
        # ),
        # migrations.AddField(
        #     model_name='user',
        #     name='two_factor_enabled',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='user',
        #     name='two_factor_secret',
        #     field=models.CharField(blank=True, max_length=100),
        # ),
    ]
