# Generated by Django 5.0.4 on 2025-03-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_two_factor_backup_codes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_picture',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_refresh_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
