# Generated by Django 5.0.4 on 2025-03-15 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='charactermemory',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='characters.character'),
        ),
        migrations.AddField(
            model_name='characterrelationship',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='characters.character'),
        ),
        migrations.AddField(
            model_name='characterrelationship',
            name='related_character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverse_relationships', to='characters.character'),
        ),
        migrations.AlterUniqueTogether(
            name='characterrelationship',
            unique_together={('character', 'related_character')},
        ),
    ]
