# Generated by Django 5.0.4 on 2025-03-15 18:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('mood', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags for this entry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Journal entries',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('reflection', 'Self-Reflection'), ('creative', 'Creative Writing'), ('character', 'Character Development'), ('worldbuilding', 'Worldbuilding'), ('goal', 'Goal Setting'), ('gratitude', 'Gratitude'), ('general', 'General')], default='general', max_length=20)),
                ('is_system', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Template content with placeholders')),
                ('template_type', models.CharField(choices=[('daily', 'Daily Reflection'), ('gratitude', 'Gratitude Journal'), ('goal', 'Goal Setting'), ('character', 'Character Exploration'), ('dream', 'Dream Log'), ('project', 'Project Update'), ('custom', 'Custom Template')], default='custom', max_length=20)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief description of the journal')),
                ('journal_type', models.CharField(choices=[('personal', 'Personal Journal'), ('character', 'Character Journal'), ('project', 'Project Journal'), ('worldbuilding', 'Worldbuilding Journal'), ('dream', 'Dream Journal'), ('other', 'Other')], default='personal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journals', to='characters.character')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
