# Generated by Django 5.0.4 on 2025-03-16 16:22

from django.db import migrations
import uuid  # Add this import at the top

class Migration(migrations.Migration):

    dependencies = [
        ('token_management', '0005_tokenpurchase_idempotency_key_and_more'),
    ]

    operations = [
        migrations.RunPython(
            code=lambda apps, schema_editor: [
                setattr(instance, 'transaction_id', uuid.uuid4()) and instance.save()
                for instance in apps.get_model('token_management', 'TokenPurchase').objects.all()
            ],
            reverse_code=migrations.RunPython.noop
        )
    ]