# Generated by Django 5.0.4 on 2025-03-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_management', '0006_auto_20250316_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertokenlimit',
            name='monthly_limit',
            field=models.PositiveIntegerField(default=50000),
        ),
    ]
