# Generated by Django 5.0.4 on 2025-03-16 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_management', '0007_alter_usertokenlimit_monthly_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertokenlimit',
            name='token_usage_this_month',
        ),
    ]
