# Generated by Django 5.0.4 on 2025-03-16 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_management', '0008_remove_usertokenlimit_token_usage_this_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertokenlimit',
            name='token_renewal_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 15, 19, 50, 39, 617785, tzinfo=datetime.timezone.utc)),
        ),
    ]
