# Generated by Django 5.0.4 on 2025-03-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_management', '0009_usertokenlimit_token_renewal_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertokenlimit',
            name='token_renewal_date',
        ),
    ]
