# Generated by Django 5.0.4 on 2025-03-16 20:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_management', '0010_remove_usertokenlimit_token_renewal_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_usage', models.IntegerField()),
                ('allocated_limit', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.RemoveField(
            model_name='usertokenlimit',
            name='token_reset_date',
        ),
        migrations.AddField(
            model_name='usertokenlimit',
            name='current_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertokenlimit',
            name='has_seen_conversion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertokenlimit',
            name='is_trial',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usertokenlimit',
            name='trial_days',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='usertokenlimit',
            name='trial_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='usertokenlimit',
            index=models.Index(fields=['user'], name='token_manag_user_id_f17c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='usertokenlimit',
            index=models.Index(fields=['is_trial'], name='token_manag_is_tria_68eae2_idx'),
        ),
        migrations.AddField(
            model_name='tokenhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tokenhistory',
            index=models.Index(fields=['user', 'year', 'month'], name='token_manag_user_id_c19cf0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tokenhistory',
            unique_together={('user', 'month', 'year')},
        ),
    ]
